### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by IdrissDimson** [liri-project/liri-project.github.io#10]
This is something I'll fix. Some of the code used in the website is quite unconventional and kinda messy. I'm going to be working on refactoring backend code. This should make it easier to implement enhancements and will calm down my code OCD (a phrase i made up :P).

**Comment by IdrissDimson** [comment]
This'll be a long term thing so im closing for now

**Comment by pierremtb** [comment]
@VirusKA Yeah you're right some codes are messy or repetitive, I tried to write it as fast as possible, so... But it'd be cool if you could clean it ;)

**Comment by IdrissDimson** [comment]
I'll do some work today
