### ISSUE TITLE
[index.html] removed unnecessarily link to index.html

### ISSUE THREAD

**Issue by deadbaed** [liri-project/liri-project.github.io#17]
here's the patch, just download the patch, apply it with "git am < phil-index.patch" and push :)

https://gist.githubusercontent.com/ploctaux/447f4a4e7f31e53ef6d4/raw/34201711bc703d0539eb26beb34d289126ae076e/phil-index.patch

**Comment by deadbaed** [comment]
maybe you don't like patches? do you want a pr instead? :)

**Comment by pierremtb** [comment]
Wow sorry I missed this one. Could you make a PR ? I'm busy AF ATM, so it would be awesome if you could. 
I will completely rewrite the website ASAP BTW.

**Comment by deadbaed** [comment]
ok no problem!
closing this
